# Intro to Numpy

In [1]:
import numpy as np
example_1 = np.array([[1,2,3], [4,5,6]])
example_1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
type(example_1) # Check type of the array

numpy.ndarray

In [5]:
example_1.shape # Check dimensions of the array

(2, 3)

In [6]:
example_1.size # Check the number of array elements 

6

**Create Values**

In [28]:
np.zeros(2) # Create an array with zeros

array([0., 0.])

In [10]:
np.arange(0,30,3) # Values between 0 and 30 with an interval of 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [11]:
np.linspace(0,10,4) # Values between 0 and 10 with equal interval

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [12]:
np.random.randint(0,30,6) # Generate 6 integers between 0 and 30

array([29, 16, 29, 26,  1, 23])

In [15]:
example_2 = np.random.randint(0,30,6).reshape(3,2) # Organize one line in a Dataframe(3,2)
example_2

array([[12, 15],
       [27, 25],
       [ 9, 19]])

**Numpy Operations**

In [17]:
example_1.max() # Max value

6

In [18]:
example_1.argmax() # Position of max element in array

5

In [19]:
example_1.mean() # Mean of array

3.5

In [20]:
example_1.std() # Standard deviation

1.707825127659933

In [22]:
sum_arrays = example_1 + example_1 # Sum arrays
sum_arrays

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [24]:
mult_arrays = example_1 * example_1 # Multiply arrays
mult_arrays

array([[ 1,  4,  9],
       [16, 25, 36]])

In [26]:
exp_arrays = example_1 ** 2 # Exponential of array
exp_arrays

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

**Select and Change Values**

In [29]:
example_1[1][1] # Select line 1 and column 1

5

In [30]:
example_1[example_1>4] # Select all elements in array > 4

array([5, 6])

In [31]:
example_1[1][0] = 10 # Change the element in this index of array
example_1

array([[ 1,  2,  3],
       [10,  5,  6]])

In [35]:
example_1 = np.insert(example_1,1,[0,0,1],axis=0)
example_1

array([[ 1,  2,  3],
       [ 0,  0,  1],
       [ 0,  0,  1],
       [ 0,  0,  1],
       [10,  5,  6]])

**Indexing and Slicing**

In [47]:
example_1[0][0:2] # Select first colunm and lines 0 and 2

array([1, 2])

In [46]:
example_1[0:][-1] # Select all columns (0:) and last line

array([10,  5,  6])